### ISSUE TITLE
README.md: support & feedback: first 2 links are not accessible

### ISSUE THREAD

**Issue by dEEf** [DevExpress/dashboard-extension-online-map-item#1] opened 2017-03-29 13:00 UTC
isc.devexpress.com is not accessible, documentation can not be viewed.

applies to:
- dashboard-extension-online-map-item
- dashboard-extension-webpage-item
- dashboard-extension-funnel-d3-item

**Comment by ghost** [comment] 2017-03-29 13:53
Thank you for your report.
The issue is now fixed.

**Closed as completed by ghost** 2017-03-29 13:53 UTC
